baseURL = "https://cosmic-crostata-81ad2e.netlify.app"
languageCode = "en-us"
title = "SmplyTitle"
copyright = "SmplyTile, Inc. 2023"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site params
[params]
  logo = "img/site-logo.svg"
  email = "info@smplytitle.com"
  # Meta data
  description = "SmplyTitle is the only title and escrow closing company that connects directly with the buyer and seller. What does that mean? It means you get better pricing, transparency and clear understanding and simply process all with the click of a button."
  author = "SmplyTitle"

  # Hubspot data
  hubspotFormApi = "https://api.hsforms.com/submissions/v3/integration/submit"
  hubspotPortalId = "23474905"
  hubspotContactFormId = "5c17587b-7c14-4b96-bb76-f5f2a2235074"
  hubspotGetInTouchFormId = "821d7d10-8d07-48b1-8484-fee137530642"
  hubspotSubscriptioFormId = "d75b929f-cfb6-45f8-b3c9-4f79cf8508b7"

  # Home top intro
  [params.homeIntro]
    title = "Welcome to the future of title insurance."
    img_url_1 = "img/home-top-img.jpg"
    img_alt_1 = "For sale"
    img_url_2 = "img/home-img-1.jpg"
    img_alt_2 = "Home family Image"
    btn_text = "Stay up to date"
    btn_url = "/subscribe/"

  # Home why choose us
  [params.homeWhyUs]
    title_left_part = "Why"
    title_right_part = "SmplyTitle?"
    img_url = "img/home-img-2.jpg"
    img_alt = "Why SmplyTitle image"
    text_p_1 = "With so much going on around a home sale, we want to take the confusion and hassle out of the process and save your clients money."
    text_p_2 = "At SmplyTitle we’re built as a digital first company. What does that mean for your clients? We’re focused on making everything as simple, clear and efficient as possible."
    btn_text = "Learn more about our approach..."
    btn_url = "/why-smplytitle/"
    # All features are defined in their own files.
    # You can find example items at data/features.

  # Home founder
  [params.founder]
    note = "Note from the founder"
    title = "It was too complicated, and too expensive."
    text_p_1 = "When I bought my first home — the whole process felt so opaque. There were fees upon fees. But for what? So I did a little digging, which confirmed what I suspected. There are lots of inflated fees for processes that are stuck in the middle of last century."
    text_p_2 = "I started SmplyTitle to bring technology and transparency to the problem, simplifying the process, reducing fees, and empowering people with knowledge to better understand every step in the home-buying journey."
    author = "- Alex Lyman - CEO & Founder"
    company_name = "SmplyTitle"
    img_url = "img/sign.png" 
    img_alt = "CEO & Founder sign image"
    btn_text = "Stay up to date"
    btn_url = "/subscribe/"

  # Home costs
  [params.costs]
    title = "Compare your costs"
    note = "Approximate costs based on home purchase price of $500,000"
    [[params.costs.item]]
      title = "SmplyTitle Costs"
      price = "$2,395"
      width = "55%"
    [[params.costs.item]]
      title = "First American Title Costs"
      price = "$3,395"
      width = "85%"
    [[params.costs.item]]
      title = "Old Republic Costs"
      price = "$3,195"
      width = "75%"
    [[params.costs.item]]
      title = "Stewart Title Costs"
      price = "$2,995"
      width = "65%"
  
  # Home trust
  [params.trust]
    img = "img/home-img-5.png"
    img_alt = "Home image"
    title = "Attorney Opinion Letters"
    description = "With the introduction of A.O.L’s to replace title insurance policies with Fannie Mae and Freddie Mac backed loans SmplyTitle has the ability to help your clients save even more money on their closing costs."

  # Home about company
  [params.about]
    title = "We’re not your father’s company or your grandfathers."
    description = "At <span>SmplyTitle</span> we’re re-inventing everything around your home buying experience. Starting with title. How you ask? We’re in the all digital, easy all the time frame of mind."
    btn_text = "Learn more about our technology"
    btn_url = "/why-smplytitle/"
    big_img = "img/home-img-3.jpg"
    big_img_alt = "Home image"
  
  # Home partners
  [params.partners]
    title_left_part = "You’re in"
    title_right_part = "good hands"
    description = "SmplyTitle is fully regulated, insured and underwritten by the most trusted names on the planet."
    [[params.partners.item]]
      img_url = "img/pt-img-1.png"
      img_alt = "Westcor partner image"
    [[params.partners.item]]
      img_url = "img/pt-img-2.png"
      img_alt = "First National partner image"

# Menu
[menu]
  [[menu.main]]
    identifier = "what-is-my-title"
    name = "What’s my title?"
    url = "/what-is-my-title/"
    weight = 1
  [[menu.main]]
    identifier = "why-smplytitle"
    name = "Why SmplyTitle"
    url = "/why-smplytitle/"
    weight = 2
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    identifier = "contact-us"
    name = "Contact us"
    url = "/contact-us/"
    weight = 4
