baseURL = "http://example.org/"
languageCode = "en-us"
title = "SmplyTitle"
copyright = "SmplyTile, Inc. 2022"

# Site params
[params]
  logo = "img/site-logo.svg"
  email = "info@smplytitle.com"
  # Meta data
  description = "SmplyTitle is the only title and escrow closing company that connects directly with the buyer and seller. What does that mean? It means you get better pricing, transparency and clear understanding and simply process all with the click of a button."

  # Home top intro
  [params.homeIntro]
    title = "What the heck is title insurance anyway?"
    img_url_1 = "img/home-top-img.jpg"
    img_alt_1 = "For sale"
    img_url_2 = "img/home-img-1.jpg"
    img_alt_2 = ""
    btn_text = "Learn more about title insurnace."
    btn_url = "#"

  # Home why choose us
  [params.homeWhyUs]
    title_left_part = "Why"
    title_right_part = "SmplyTitle?"
    img_url = "img/home-img-2.jpg"
    img_alt = ""
    text_p_1 = "With so much going on around a home sale, we want to take the confusion and hassle out of the process and save you money."
    text_p_2 = "By simply providing a few details about the size of a sale, we can instantly give you a comparative analysis of fees from multiple companies. And we can beat them all."
    btn_text = "Learn how we can help"
    btn_url = "#"
    # All features are defined in their own files.
    # You can find example items at data/features.

  # Home founder
  [params.founder]
    note = "Note from the founder"
    title = "It was too complicated, and too expensive."
    text_p_1 = "When I bought my first home — the whole process felt so opaque. There were fees upon fees. But for what? So I did a little digging, which confirmed what I suspected. There are lots of inflated fees for processes that are stuck in the middle of last century."
    text_p_2 = "I started SmplyTitle to bring technology and transparency to the problem, simplifying the process, reducing fees, and empowering people with knowledge to better understand every step in the home-buying journey."
    author = "- Alex Lyman - CEO & Founder"
    company_name = "SmplyTitle"
    img_url = "img/sign.png" 
    img_alt = "sign"


# Menu
[menu]
  [[menu.main]]
    identifier = "buying"
    name = "Buying"
    url = "/buying"
    weight = 1
  [[menu.main]]
    identifier = "why-smplytitle"
    name = "Why SmplyTitle"
    url = "/why-smplytitle"
    weight = 2
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq"
    weight = 3
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 4
  [[menu.main]]
    identifier = "contact-us"
    name = "Contact us"
    url = "/contacts"
    weight = 4
